#!/bin/bash
valgrind --track-fds=yes --leak-check=full --show-leak-kinds=all --track-origins=yes --trace-children=yes --suppressions=/mnt/nfs/homes/yuboktae/CURSUS_42/minishell/minishell.supp ./minishell

